# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Item.create([
  { :name => nil, :description => nil, :product_model_number => nil, :vendor => nil, :quantity => nil, :unit_value => 0.0, :value => 0.0, :picture => nil, :url => nil, :location => nil, :created_at => nil, :updated_at => nil, :part_number => nil }
], :without_protection => true )



User.create([
  { :email => "", :encrypted_password => "", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 0, :current_sign_in_at => nil, :last_sign_in_at => nil, :current_sign_in_ip => nil, :last_sign_in_ip => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )


